import { View, Text, StyleSheet, Alert, Switch } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from '../../types/navigation';
import { useApp } from '../../context/AppContext';
import { useTheme } from '../../context/ThemeContext';
import ScreenWrapper from '../../components/ScreenWrapper';
import Card from '../../components/Card';
import CustomButton from '../../components/CustomButton';

type Props = { navigation: NativeStackNavigationProp<RootStackParamList, 'UserTabs'> };
export default function ProfileScreen({ navigation }: Props) {
  const { colors, theme, toggleTheme } = useTheme(); const { user, vehicles, maintenances, logout } = useApp();
  const handleLogout = () => Alert.alert('Cerrar sesión', '¿Deseas cerrar tu sesión?', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Cerrar sesión', style: 'destructive', onPress: () => { logout(); navigation.reset({ index: 0, routes: [{ name: 'Login' }] }); } }]);
  return <ScreenWrapper><View style={styles.header}><View style={[styles.avatar, { backgroundColor: colors.primarySoft }]}><Ionicons name="person" size={34} color={colors.primary} /></View><Text style={[styles.title, { color: colors.text }]}>Mi perfil</Text><Text style={[styles.subtitle, { color: colors.secondaryText }]}>Información de tu cuenta</Text></View><Card><Text style={[styles.name, { color: colors.text }]}>{user?.name || 'Usuario'}</Text><Text style={[styles.email, { color: colors.secondaryText }]}>{user?.email || ''}</Text></Card><View style={styles.stats}><Card><Text style={[styles.number, { color: colors.primary }]}>{vehicles.length}</Text><Text style={[styles.statLabel, { color: colors.secondaryText }]}>Vehículos</Text></Card><Card><Text style={[styles.number, { color: colors.primary }]}>{maintenances.length}</Text><Text style={[styles.statLabel, { color: colors.secondaryText }]}>Mantenimientos</Text></Card></View><Card><View style={styles.themeRow}><View style={[styles.themeIcon, { backgroundColor: colors.primarySoft }]}><Ionicons name={theme === 'dark' ? 'moon-outline' : 'sunny-outline'} size={22} color={colors.primary} /></View><View style={styles.themeInfo}><Text style={[styles.themeTitle, { color: colors.text }]}>Modo oscuro</Text><Text style={[styles.themeDescription, { color: colors.secondaryText }]}>{theme === 'dark' ? 'Tema oscuro activado' : 'Tema claro activado'}</Text></View><Switch value={theme === 'dark'} onValueChange={toggleTheme} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={theme === 'dark' ? '#FFFFFF' : colors.surface} /></View></Card><CustomButton title="Cerrar sesión" variant="danger" icon="log-out-outline" onPress={handleLogout} /></ScreenWrapper>;
}
const styles = StyleSheet.create({ header: { alignItems: 'center', marginBottom: 22 }, avatar: { width: 76, height: 76, borderRadius: 38, justifyContent: 'center', alignItems: 'center', marginBottom: 12 }, title: { fontSize: 28, fontWeight: '800' }, subtitle: { marginTop: 4 }, name: { fontSize: 20, fontWeight: '800', textAlign: 'center' }, email: { fontSize: 14, textAlign: 'center', marginTop: 5 }, stats: { flexDirection: 'row', gap: 10 }, number: { fontSize: 25, fontWeight: '800', textAlign: 'center' }, statLabel: { fontSize: 12, textAlign: 'center', marginTop: 4 }, themeRow: { flexDirection: 'row', alignItems: 'center' }, themeIcon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', marginRight: 12 }, themeInfo: { flex: 1 }, themeTitle: { fontSize: 16, fontWeight: '700' }, themeDescription: { fontSize: 13, marginTop: 3 } });
