import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from '../../types/navigation';
import { useTheme } from '../../context/ThemeContext';
import { useApp } from '../../context/AppContext';
import ScreenWrapper from '../../components/ScreenWrapper';
import Card from '../../components/Card';

type Props = { navigation: NativeStackNavigationProp<RootStackParamList, 'UserTabs'> };
export default function RemindersScreen({ navigation }: Props) {
  const { colors } = useTheme(); const { vehicles, maintenances } = useApp();
  const reminders = maintenances.map((item) => { const vehicle = vehicles.find((v) => v.id === item.vehicleId); const current = vehicle?.mileage ?? item.mileage; return { item, vehicle, remaining: item.nextMileage - current }; }).sort((a, b) => a.remaining - b.remaining);
  return <ScreenWrapper><View style={styles.header}><View><Text style={[styles.title, { color: colors.text }]}>Recordatorios</Text><Text style={[styles.subtitle, { color: colors.secondaryText }]}>Controla tus próximos servicios</Text></View><Ionicons name="notifications-outline" size={36} color={colors.primary} /></View>{reminders.length === 0 ? <Card><Ionicons name="checkmark-circle-outline" size={46} color={colors.success} style={styles.emptyIcon} /><Text style={[styles.emptyTitle, { color: colors.text }]}>Todo está tranquilo</Text><Text style={[styles.emptyText, { color: colors.secondaryText }]}>Registra un mantenimiento para comenzar a recibir recordatorios.</Text></Card> : reminders.map(({ item, vehicle, remaining }) => { const overdue = remaining <= 0; return <TouchableOpacity key={item.id} activeOpacity={0.85} onPress={() => navigation.navigate('ReminderDetail', { vehicleId: item.vehicleId, maintenanceId: item.id })}><Card><View style={styles.row}><View style={[styles.status, { backgroundColor: overdue ? colors.dangerSoft : colors.warningSoft }]}><Ionicons name={overdue ? 'alert-outline' : 'time-outline'} size={22} color={overdue ? colors.danger : colors.warning} /></View><View style={styles.info}><Text style={[styles.type, { color: colors.text }]}>{item.type}</Text><Text style={[styles.vehicle, { color: colors.secondaryText }]}>{vehicle?.name || 'Vehículo'}</Text><Text style={{ color: overdue ? colors.danger : colors.warning, fontSize: 12, fontWeight: '700', marginTop: 4 }}>{overdue ? `Pendiente · ${Math.abs(remaining).toLocaleString()} km excedidos` : `Faltan ${remaining.toLocaleString()} km`}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.placeholder} /></View></Card></TouchableOpacity>; })}</ScreenWrapper>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 }, title: { fontSize: 28, fontWeight: '800' }, subtitle: { marginTop: 4 }, emptyIcon: { alignSelf: 'center', marginBottom: 10 }, emptyTitle: { textAlign: 'center', fontSize: 19, fontWeight: '800' }, emptyText: { textAlign: 'center', lineHeight: 21 }, row: { flexDirection: 'row', alignItems: 'center' }, status: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 12 }, info: { flex: 1 }, type: { fontWeight: '800', fontSize: 16 }, vehicle: { fontSize: 13, marginTop: 3 } });
